module.exports = {
  a: "asdqwz",
  b: "cvbnmgh",
  c: "zxcvbdf",
  d: "asdfgwerxc",
  e: "qwertsdf",
  f: "fghretcv",
  g: "dfghjrtyvb",
  h: "fghjktyubn",
  i: "yuiopkjl",
  j: "ghjklyuinm",
  k: "hjklñuiom",
  l: "jklñiop",
  m: "bnmjk",
  n: "vbnmhj",
  o: "uipoklñ",
  p: "ioplñ",
  q: "qweas",
  r: "wertydfg",
  s: "asdfqwezx",
  t: "ertyufgh",
  u: "tyuiohjk",
  v: "xcvbnfg",
  w: "qwerasd",
  x: "zxcvsd",
  y: "rtyuighj",
  z: "asxcz",
};
